### ISSUE TITLE
Function "__v_p4d_alloc_ext4" not found

### ISSUE THREAD

**Issue by RiweiPan** [multifacet/Bypassd#1]
Hi, thanks for the excellent works on direct-access SSD!
I want to reproduce your codes in my machine but I encountered an issue in compiling. 
```
Bypassd/kernel/linux-5.4/fs/ext4/./swiftcore/swiftcore_pt.h:55: undefined reference to `__v_p4d_alloc_ext4'
```
After searching the codes, I still could not find the definition about this function. 
Could you give me suggestion to address this issue? Thanks a lot!

**Comment by SujayYadalam94** [comment]
This is weird. Are you using your own config while compiling kernel?
Can you try using the [config](https://github.com/SujayYadalam94/bypassd_kernel/blob/a26062f07735e2b265a3c9d87d4df3a8ce77b7b2/config_used_for_eval) attached in the repo?

**Comment by RiweiPan** [comment]
Thank you for your suggestion. I use the script `bash utils/build_linux_kernel.sh ` to build the kernel. 
I will try the given .config. Thanks a lot for your help.

**Comment by RiweiPan** [comment]
Fixed the issue using the given .config
